using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _0408ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.ForegroundColor = ConsoleColor.Blue;Console.Write("namespace");
            Console.ForegroundColor = ConsoleColor.White;Console.Write("ConsoleApp1");
            Console.WriteLine("\n{");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("    class");
            Console.ForegroundColor = ConsoleColor.Cyan;Console.Write("  Program");
            Console.ForegroundColor = ConsoleColor.White; Console.WriteLine("\n   {");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("       static void");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("  Main");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Blue; Console.Write("string");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("[]");
            Console.ForegroundColor = ConsoleColor.DarkBlue; Console.Write("args");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(")");
            Console.WriteLine("\n       {");     
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          //單行註解");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          //*");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          多行註解");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          123");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          456");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          789");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          HAHA");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          HEHE");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          */");
            Console.WriteLine();
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write("          System.");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"Hello World!!\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write("          System.");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"Hi,這是第一個Console程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"C# 語言第一個示範\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"C# Demo\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("ForegroundColor");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("=");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("ConsoleColor.");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("Yellow");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("BackgroundColor");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("=");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("ConsoleColor.");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("DarkBlue");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(";");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"1.主控台應用程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"2.Windows Form 應用程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"3.Web 應用程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("();");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("   //換行;");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("();");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("ResetColor");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("();");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("  //回到原本的顏色");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"特殊字元符號\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"\\\"雙引號\\\"\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("   //反斜線可以代表特殊符號");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"\\\\反斜線\\\\\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"'單引號'\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("   //單引號代表字元(有含義是特殊符號)，雙引號是字串");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"\\+t+縮排\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("   //Tab的意思，4個字元");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"\\t12345縮排\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"\\t\\t\\t+縮排");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"\\n換行\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("   //\\n換行");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"換行\\n\\n\\n\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("          Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("(");
            Console.ForegroundColor = ConsoleColor.Magenta; Console.Write("\"按Enter結束程式\"");
            Console.ForegroundColor = ConsoleColor.White; Console.Write(");");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          //有定義的命名空間可以省(System");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Gray; Console.Write("          System.");
            Console.ForegroundColor = ConsoleColor.Cyan; Console.Write("Console.");
            Console.ForegroundColor = ConsoleColor.Yellow; Console.Write("WriteLine");
            Console.ForegroundColor = ConsoleColor.White; Console.Write("();");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.Green; Console.Write("          //讀取使用者輸入，等待讀取一整行");
            Console.WriteLine();
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.White; Console.Write("        }");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.White; Console.Write("    }");
            Console.WriteLine();
            Console.ForegroundColor = ConsoleColor.White; Console.Write("}");


            System.Console.ReadLine();


        }
    }
}
